# Generated by Django 4.2 on 2026-03-01 18:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='jobapplication',
            options={'ordering': ['-application_date']},
        ),
        migrations.RenameField(
            model_name='jobapplication',
            old_name='submitted_at',
            new_name='application_date',
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='deadline',
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal notes about the applicant'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected'), ('hired', 'Hired')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='application_deadline',
            field=models.DateField(default=datetime.date(2026, 3, 1), help_text='Last date to apply', verbose_name='Deadline'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobposting',
            name='benefits',
            field=models.TextField(blank=True, help_text='Benefits offered (health, 401k, etc.)'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='requirements',
            field=models.TextField(blank=True, help_text='List of required qualifications and skills'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='responsibilities',
            field=models.TextField(blank=True, help_text='Key duties and responsibilities'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='salary_range',
            field=models.CharField(blank=True, help_text='e.g. $50,000 - $70,000 per year', max_length=100),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='description',
            field=models.TextField(help_text='Brief overview of the role'),
        ),
    ]
