# Generated by Django 4.2 on 2026-03-19 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0002_contactmessage_alter_jobapplication_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='application_deadline',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='benefits',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='requirements',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='responsibilities',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='salary_range',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
