# Generated by Django 4.2 on 2026-03-20 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0003_alter_jobapplication_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('home', 'Home'), ('careers', 'Careers')], default='home', max_length=20)),
                ('visited_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-visited_at'],
            },
        ),
        migrations.CreateModel(
            name='JobView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='jobapp.jobposting')),
            ],
            options={
                'ordering': ['-viewed_at'],
            },
        ),
    ]
